# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_auto_20171028_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendance',
            name='attend',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent')], default='absent', max_length=6),
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
